build-report.outputs.reportame: Trivy
description: "Run a Trivy Scan and upload the results"

inputs:
  scan-type:
    description: "type of scan: image or fs"
    required: true
    type: string
  image-ref:
    description: "image to scan (required if scan-type is image)"
    type: string
  scan-ref:
    description: "path to scan (required if scan-type is fs)"
    type: string
  timeout:
    default: 15m
    type: string
  vuln-type:
    default: "os,library"
    type: string
  severity:
    default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
    type: string
  pr-comment:
    default: true
    type: boolean
  skip-dirs:
    type: string
  skip-setup:
    default: false
    type: boolean

outputs:
  text-report:
    description: "text report of trivy scan"
    value: ${{ steps.build-report.outputs.report }}
  sarif-file:
    description: "sarif report from trivy scan"
    value: ${{ steps.convert-sarif.outputs.sarif }} 
runs:
  using: "composite"
  steps:
    - name: Validate Required Inputs
      shell: bash
      run: |
        if [[ "${{ inputs.scan-type }}" == "image" && -z "${{ inputs.image-ref }}" ]]; then
          echo "::error::scan-type=image requires image-ref"
          exit 1
        elif [[ "${{ inputs.scan-type }}" == "fs" && -z "${{ inputs.scan-ref }}" ]]; then
          echo "::error::scan-type=fs requires scan-ref"
          exit 1
        elif [[ "${{ inputs.scan-type }}" != "image" && "${{ inputs.scan-type }}" != "fs" ]]; then
          echo "::error::scan-type must be either 'image' or 'fs'"
          exit 1
        fi

    - name: Derive Report Name
      id: report-name
      env:
        IMAGE: ${{ inputs.image-ref }}
        SCAN_REF: ${{ inputs.scan-ref }}
      shell: bash
      run: |
        if [ -n "$IMAGE" ]; then
          basename="$(basename $IMAGE)"
          stripped_name="${basename%:*}-${basename##*:}-${{ github.run_id }}"
        else 
          echo "scan_ref is $SCAN_REF"
          if [ "$SCAN_REF" == "." ]; then
            SCAN_REF=$(pwd)
          fi
          basename="$(basename $SCAN_REF)"
          stripped_name="${basename}-${{ github.run_id }}"
        fi
        echo "name=$stripped_name" >> $GITHUB_OUTPUT

    - name: Run Trivy Scan
      id: trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: ${{ inputs.scan-type }}
        image-ref: ${{ inputs.image-ref }}
        scan-ref: ${{ inputs.scan-ref }}
        timeout: ${{ inputs.timeout }}
        vuln-type: ${{ inputs.vuln-type }}
        severity: ${{ inputs.severity }}
        format: json
        output: ${{ steps.report-name.outputs.name }}.json
        skip-dirs: ${{ inputs.skip-dirs }}
        skip-setup-trivy: ${{ inputs.skip-setup }}


    - name: Upload JSON Report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.report-name.outputs.name }}-${{ inputs.scan-type }}-trivy
        path: ${{ steps.report-name.outputs.name  }}.json

    - name: Convert Report to Text
      if: ${{ inputs.summary || inputs.pr-comment }}
      id: convert-text
      env:
        text-file: ${{ steps.report-name.outputs.name }}.txt
        json-file: ${{ steps.report-name.outputs.name }}.json
      shell: bash
      run: |

        trivy convert --format table --output ${{ env.text-file }} ${{ env.json-file }}
        
        if [ "$(stat -c%s ${{ env.text-file }})" -gt 0 ]; then
	  echo "111111"
          echo "text=${{ env.text-file }}" >> $GITHUB_OUTPUT
        else
	  echo "222222"
          echo "text=" >> $GITHUB_OUTPUT  # Explicitly unset the output
        fi

    - name: Build Report for PR and Summary
      if: steps.convert-text.outputs.text != ''
      id: build-report
      shell: bash
      run: |
        REPORT_FILE="report.txt"
        echo "Trivy Scan Output" > $REPORT_FILE
        echo "Scan Type: ${{ inputs.scan-type }}" >> $REPORT_FILE
        TARGET="${{ inputs.image-ref || inputs.scan-ref }}"
        echo "Target: $TARGET" >> $REPORT_FILE
        echo "Report Artifact Name: ${{ steps.report-name.outputs.name }}-${{ inputs.scan-type }}-trivy" >> $REPORT_FILE
        echo "<details><summary>Click to expand</summary>" >> $REPORT_FILE
        echo "" >> $REPORT_FILE
        echo '```' >> $REPORT_FILE
        cat ${{ steps.convert-text.outputs.text }} >> $REPORT_FILE
        echo '```' >> $REPORT_FILE
        echo "</details>" >> $REPORT_FILE
        echo "report=$REPORT_FILE" >> $GITHUB_OUTPUT

    - name: Post Scan Results to GitHub PR
      if: github.event_name == 'pull_request' && inputs.pr-comment == true && steps.build-report.outputs.report != ''
      uses: mshick/add-pr-comment@v2
      with:
        allow-repeats: true
        message-id: Trivy Scan
        message-path: ${{ steps.build-report.outputs.report }}

    - name: Convert to SARIF
      id: convert-sarif
      shell: bash
      run: |
        trivy convert --format sarif --output ${{ steps.report-name.outputs.name }}.sarif ${{ steps.report-name.outputs.name }}.json
        echo "sarif=${{ inputs.output-file }}.sarif" >> $GITHUB_OUTPUT


