name: Trivy
description: "Run a Trivy Scan and upload the results"
inputs:
  image-ref:
    description: "image to scan"
    required: false
    type: string
  scan-type:
    description: "type of scan"
    required: true
    type: string
  scan-ref:
    description: "path to scan for scan-type fs"
    type: string
  timeout:
    description: "how long to scan"
    default: 15m
    type: string
  vuln-type:
    description: "types of vulnerabilities to report"
    default: "os,library"
    type: string
  severity:
    description: "severity of issues to report"
    default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
    type: string
  output-file:
    description: "outputfile, this is used mostly as a run level variable since not supported in composite actions"
    default: "trivy"
  summary:
    description: "enable summary output"
    default: true
    type: boolean
  pr-comment:
    description: "enable pull request comment"
    default: true
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      shell: bash
      if: ${{ inputs.scan-type == 'image' && inputs.image-ref == '' }}
      run: |
        echo "::error::scan-type of image requires image-ref"
        exit 1

    - name: Validate Inputs
      shell: bash
      if: ${{ inputs.scan-type == 'fs' && inputs.scan-ref == '' }}
      run: |
        echo "::error::scan-type of fs requires scan-ref"
        exit 1

    - name: Run Trivy vulnerability scanner
      id: scan
      uses: aquasecurity/trivy-action@master
      with:         
        scan-type: "${{ inputs.scan-type }}"
        scan-ref: "${{ inputs.scan-ref }}"
        image-ref: "${{ inputs.image-ref }}"
        timeout: "${{ inputs.timeout }}"
        vuln-type: "${{ inputs.vuln-type }}"
        severity: "${{ inputs.severity }}"
        format: "json"
        output: "${{ inputs.output-file }}.json"
        cache: false

    - name: Get name
      id: get-name
      env:
        IMAGE: ${{ inputs.image-ref }}
      shell: bash
      run: |
        if [ -n "$IMAGE" ]; then
          basename="${IMAGE##*/}"
          stripped_name="${basename%:*}"
        else 
          basename="${inputs.working-dir##*/}"
          stripped_name="$basename"
        fi
        echo "name=$stripped_name" >> $GITHUB_OUTPUT

    - name: Upload json report as artifact
      id: upload-json
      uses: actions/upload-artifact@v4
      with:
        name: "${{ steps.get-name.outputs.name }}-trivy"
        path: ${{ env.TRIVY_OUTPUT }}
       
    - name: Convert output to text for github summary and PR
      id: convert-text
      if: ${{ inputs.summary || inputs.pr-comment }}
      env:
        OUTPUT-FILE: "${{ inputs.output-file }}.txt"
      shell: bash
      run: |
        trivy convert --format table  --output ${{ env.OUTPUT-FILE }} ${{ env.TRIVY_OUTPUT }}
        echo "text-file=${{ env.OUTPUT-FILE }}" >> $GITHUB_OUTPUT

    - name: Build Report
      if: ${{ inputs.summary || inputs.pr-comment }}
      id: build-report
      shell: bash
      env:
        TRIVY-TEXT-FILE: ${{ steps.convert-text.outputs.text-file }}
        ACTOR: ${{ github.actor }}
        EVENT-NAME: ${{ github.event_name }}
        WORKFLOW: ${{ github.workflow }}
        WORKDIR:  ${{ github.workdir }}
        REPO: ${{ github.repository }}
        RUN-ID: ${{ github.run_id }}
        SCAN-TYPE: ${{ inputs.scan-type }}
      run: |
        if [ -s ${{ env.TRIVY-TEXT-FILE }} ]; then
          {
            echo "### Trivy Scan Output"
            echo "<details><summary>Click to expand</summary>"
            echo ""
            echo '```scan-type ${{ env.SCAN-TYPE }}'
            cat ${{ env.TRIVY-TEXT-FILE }}
            echo '```'
            echo "</details>"
          } >> report.txt
          echo "report=report.txt" >> $GITHUB_OUTPUT     
        fi

    - name: Post Scan Results to GitHub PR
      uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
      if: ${{ github.event_name == 'pull_request' && inputs.pr_comment && env.report != '' }}
      with:
        allow-repeats: true
        repo-token: ${{ github.token }}
        message-id: Trivy Scan ${{ github.workflow }}
        message-path: ${{ steps.build-report.outputs.report }}

    - name: Post Scan Results to Workflow Summary
      if: ${{ inputs.summary && env.report != '' }}
      shell: bash
      run: |
        cat ${{ steps.build-report.outputs.report }} >> $GITHUB_STEP_SUMMARY

    - name: Check if GHAS is enabled
      uses: actions/github-script@v7
      id: ghas-enabled
      with:
        script: |
          const response = await github.rest.repos.get({
            owner: '${{ github.repository }}'.split("/")[0],
            repo: '${{ github.repository }}'.split("/")[1]
          });
          const private = response.data.private
          
          if (private) {
            const securityEnabled = response.data.security_and_analysis?.advanced_security?.status === 'enabled';
 
            if (!securityEnabled) {
              const message = 'GitHub Advanced Security is NOT enabled and repo is private. Can not upload report, check summary';
              core.warning(message);
              return false
            }
          }
          return true

    - name: Convert output to Sarif for codescanning
      env:
        OUTPUT-FILE: ${{ inputs.output-file }}
      if: steps.ghas-enabled.output.result
      id: convert-sarif
      shell: bash
      run: |
        trivy convert --format sarif --output ${{ env.OUTPUT-FILE }}.sarif ${{ env.TRIVY_JSON }}
        echo "sarif-file=${{ env.OUTPUT-FILE }}.sarif" >> $GITHUB_OUTPUT
    
    - name: Upload Trivy scan results to GitHub Security tab
      if: steps.ghas-enabled.output.result
      id: upload
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.convert-sarif.outputs.sarif-file }}
