name: Trivy
description: "Run a Trivy Scan and upload the results"
inputs:
  app:
    description: "app name for report"
    required: true
    type: string
  image-ref:
    description: "image to scan"
    required: false
    type: string
  scan-type:
    description: "type of scan"
    required: true
    type: string
  timeout:
    description: "how long to scan"
    default: 15m
    type: string
  vuln-type:
    description: "types of vulnerabilities to report"
    default: "os,library"
    type: string
  severity:
    description: "severity of issues to report"
    default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
    type: string
  output-file:
    description: "outputfile, this is used mostly as a run level variable since not supported in composite actions"
    default: "trivy"

runs:
  using: "composite"
  steps:

    - name: Validate Inputs
      shell: bash
      env:
        SCAN_TYPE: ${{ inputs.scan-type }}
        IMAGE_REF: ${{ inputs.image-ref }}
      run: |
        if [[ ${{ env.SCAN_TYPE }} == "image" && ${{ env.IMAGE_REF }} == '' ]]; then
        {
          echo "::error::scan-type of image requires image-ref"
          exit 1
        }
        fi

    - name: Run Trivy vulnerability scanner
      id: scan
      env:
        OUTPUT-FILE: ${{ inputs.output-file }}
      uses: aquasecurity/trivy-action@master
      with:         
        scan-type: "${{ inputs.scan-type }}"
        image-ref: "${{ inputs.image-ref }}"
        timeout: "${{ inputs.timeout }}"
        vuln-type: "${{ inputs.vuln-type }}"
        severity: "${{ inputs.severity }}"
        format: "json"
        output: "${{ env.OUTPUT-FILE }}.json"

    - name: Check if trivy output scan exists
      shell: bash
      env:
        OUTPUT-FILE: ${{ inputs.output-file }}
      run: |
        jq -f ${{ env.OUTPUT-FILE }} '.Results[]'
        if [ ! -s "${{ env.OUTPUT-FILE }}.json" !! jq -f ${{ env.OUTPUT-FILE }} '.Results[]' = "null" ]; then
          echo "::error::Could not find trivy results, scan failed"
          exit 1
        fi  

    - name: Convert output to text for github summary
      env:
        OUTPUT-FILE: ${{ inputs.output-file }}
      id: convert-text
      shell: bash
      run: |
        trivy convert --format table  --output ${{ env.OUTPUT-FILE }}.txt ${{ env.OUTPUT-FILE }}.json
        echo "text-file=${{ env.OUTPUT-FILE }}.txt" >> $GITHUB_OUTPUT

    - name: Publish Trivy Output to Summary
      shell: bash
      env:
        APP: ${{ inputs.app }}
      run: |
        echo "## Trivy Scan Results for ${{ env.APP }}" >> $GITHUB_STEP_SUMMARY
        if [[ -s "${{ steps.convert-text.outputs.text-file }}" ]]; then
        {
          echo "<details><summary>Click to expand</summary>"
          echo ""
          echo "```Scan results"
          cat "${{ steps.convert-text.outputs.text-file }}"
          echo "```"
          echo "</details>"
        } >> $GITHUB_STEP_SUMMARY
        else
          echo "No issues found" >> $GITHUB_STEP_SUMMARY
        fi

    - name: Check if GHAS is enabled
      uses: actions/github-script@v7
      id: ghas-enabled
      with:
        script: |
          const response = await github.rest.repos.get({
            owner: '${{ github.repository }}'.split("/")[0],
            repo: '${{ github.repository }}'.split("/")[1]
          });
          const private = response.data.private
          
          if (private) {
            const securityEnabled = response.data.security_and_analysis?.advanced_security?.status === 'enabled';
 
            if (!securityEnabled) {
              const message = 'GitHub Advanced Security is NOT enabled and repo is private. Can not upload report, check summary';
              core.warning(message);
              return false
            }
          }
          return true

    - name: Convert output to Sarif for codescanning
      env:
        OUTPUT-FILE: ${{ inputs.output-file }}
      if: steps.ghas-enabled.output.result
      id: convert-sarif
      shell: bash
      run: |
        trivy convert --format sarif --output ${{ env.OUTPUT-FILE }}.sarif trivy.json
        echo "sarif-file=${{ env.OUTPUT-FILE }}.sarif" >> $GITHUB_OUTPUT
    
    - name: Upload Trivy scan results to GitHub Security tab
      if: steps.ghas-enabled.output.result
      id: upload
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.convert-sarif.outputs.sarif-file }}

